version: "3.7"

services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db_data:/bitnami/mariadb
  wordpress:
    image: bitnami/wordpress-nginx:latest
    environment:
      - WORDPRESS_DATABASE_HOST=db
      - WORDPRESS_DATABASE_NAME=wordpress
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8000:8080"
    volumes:
      - ./wordpress_data:/bitnami/wordpress
    depends_on:
      - db